describe('login', () => {
    beforeEach(() => {
        cy.visit('https://petstore.octoperf.com/actions/Account.action')
    })

    it('TC-01', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
    })
    it('TC-02', () => {
        cy.get('[name="username"]').type('username')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
    })
    it('TC-03', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('passwork')
        cy.get('[name="signon"]').click()
    })
    it('TC-04', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=FISH"] > img').click()
    })
    it('TC-05', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=DOGS"] > img').click()
    })
    it('TC-06', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=CATS"] > img').click()
    })
    it('TC-07', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=REPTILES"] > img').click()
    })
    it('TC-08', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=BIRDS"] > img').click()
    })
    it('TC-09', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=BIRDS"] > img').click()
        cy.get('tbody > :nth-child(2) > :nth-child(1) > a').click()
        cy.get('.Button').click()
        cy.get(':nth-child(8) > .Button').click()
    })
    it('TC-10', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=BIRDS"] > img').click()
        cy.get('tbody > :nth-child(2) > :nth-child(1) > a').click()
        cy.get('.Button').click()
        cy.get('[colspan="7"] > input').click()
    })
    it('TC-11', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=BIRDS"] > img').click()
        cy.get('tbody > :nth-child(2) > :nth-child(1) > a').click()
        cy.get('.Button').click()
        cy.get('[href="/actions/Order.action?newOrderForm="]').click()
        cy.get('[name="newOrder"]').click()
        cy.get('.Button').click()
        cy.get('#LogoContent > a > img').click()
    })
    it('TC-12', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('#SidebarContent > [href="/actions/Catalog.action?viewCategory=&categoryId=BIRDS"] > img').click()
        cy.get('[href="/actions/Catalog.action?viewCategory=&categoryId=FISH"] > img').click()
        cy.get('[href="/actions/Catalog.action?viewCategory=&categoryId=DOGS"] > img').click()
    })
    it('TC-13', () => {
        cy.get('[name="username"]').type('j2ee')
        cy.get('[name="password"]').clear()
        cy.get('[name="password"]').type('j2ee')
        cy.get('[name="signon"]').click()
        cy.get('[href="/actions/Account.action?signoff="]').click()
    })
    


})